

# This file was *autogenerated* from the file /home/sage/repo/challenges/Real Number Generator/verify_reduction.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_48 = Integer(48); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0'); _sage_const_4 = Integer(4); _sage_const_120 = Integer(120); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_70 = Integer(70); _sage_const_2000 = Integer(2000); _sage_const_300 = Integer(300)
from sage.all import *
import struct
import math
from decimal import getcontext, Decimal as D
import random

getcontext().prec = int(_sage_const_100 )

class RealNumberGenerator():
    def __init__(self, seed):
        self.state = seed

    def random(self):
        self.state = D(math.e) * D(str(self.state)) % D(math.pi)
        return math.sqrt(math.fabs(math.sin(D(str(self.state))) + math.cos(D(str(self.state)))))

    def next_bytes(self):
        while True:
            r = self.random()
            B = struct.pack('d', r)
            for b in B:
                yield b

def verify_reduction():
    print("Verifying reduction logic...")
    seed = random.getrandbits(_sage_const_48 )
    print(f"True seed: {seed}")
    
    rng = RealNumberGenerator(seed)
    gen = rng.next_bytes()
    # r0 (8 bytes) + r1 (3 bytes to create context)
    stream_prefix = bytes([next(gen) for _ in range(_sage_const_16 )])
    bytes_r0 = stream_prefix[:_sage_const_8 ]
    r0 = struct.unpack('d', bytes_r0)[_sage_const_0 ]
    
    # Recover s1 (approx)
    y = r0**_sage_const_2 
    target = y / math.sqrt(_sage_const_2 )
    if target > _sage_const_1p0 : target = _sage_const_1p0 
    asin_t = math.asin(target)
    thetas = [asin_t, math.pi - asin_t, math.pi + asin_t, _sage_const_2 *math.pi - asin_t]
    
    candidates_s1 = []
    for th in thetas:
        s = th - math.pi/_sage_const_4 
        s %= (_sage_const_2 *math.pi)
        if _sage_const_0  <= s < math.pi:
            candidates_s1.append(s)

    alpha = D(math.e) / D(math.pi)
    
    # CVP to find alias
    M_CVP = int(_sage_const_2 **_sage_const_120 )
    alpha_int = int(M_CVP * alpha)
    
    found_alias = False
    aliases = []
    
    for s1_val in candidates_s1:
        beta = D(s1_val) / D(math.pi)
        beta_int = int(M_CVP * beta)
        
        L_CVP = Matrix(ZZ, [[_sage_const_1 , alpha_int], [_sage_const_0 , -M_CVP]])
        target_vec = vector(ZZ, [_sage_const_0 , beta_int])
        
        try:
            # Manual CVP
            B_red = L_CVP.LLL()
            t_vec = vector(QQ, target_vec)
            B_red_qq = B_red.change_ring(QQ)
            x = B_red_qq.solve_left(t_vec)
            from itertools import product
            c_base = [round(xi) for xi in x]
            
            # Check neighbors to find A valid alias (might not be the "closest" if noise is high)
            for delta in product(range(-_sage_const_2 , _sage_const_3 ), repeat=len(c_base)):
                c = [ci + di for ci, di in zip(c_base, delta)]
                closest_pt = vector(ZZ, c) * B_red
                coeffs = L_CVP.solve_left(closest_pt)
                extracted_s0 = coeffs[_sage_const_0 ]
                s0_cand = int(extracted_s0)
                
                # Check if this alias generates r0
                if _sage_const_0  < abs(s0_cand) < _sage_const_2 **_sage_const_70 : # Wide check
                     try:
                        trng = RealNumberGenerator(abs(s0_cand))
                        g = trng.next_bytes()
                        s_p = bytes([next(g) for _ in range(_sage_const_8 )])
                        if s_p == bytes_r0:
                             print(f"Found alias: {abs(s0_cand)}")
                             aliases.append(abs(s0_cand))
                             found_alias = True
                     except: pass
        except Exception as e:
            print(e)
            
    if not aliases:
        print("No alias found! CVP failed.")
        return

    print(f"Aliases found: {len(aliases)}")
    
    # Try reduction on aliases
    from sage.rings.real_mpfr import RealField
    RR = RealField(_sage_const_2000 )
    alpha_rr = RR(math.e)/RR(math.pi)
    cf = continued_fraction(alpha_rr)
    convs = cf.convergents()
    # Listify to check length
    convs_list = list(convs)
    print(f"Convergents count: {len(convs_list)}")
    
    for alias in aliases:
        print(f"Reducing alias {alias}")
        matched = False
        for conv in convs_list[:_sage_const_300 ]:
            q = int(conv.denominator())
            if q == _sage_const_0 : continue
            
            # Check simple reduction
            rem = alias % q
            
            checks = [rem, rem+q, rem-q, rem+_sage_const_2 *q, rem-_sage_const_2 *q]
            for cand in checks:
                if cand == seed:
                    print(f"SUCCESS! Found seed {cand} using q={q} from alias {alias}")
                    matched = True
                    return
        if not matched:
            print(f"Failed to reduce alias {alias}")

if __name__ == "__main__":
    verify_reduction()

