

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/check_prime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_33706105179137483720382763858941811011514787082216064845474913024213096359 = Integer(33706105179137483720382763858941811011514787082216064845474913024213096359)
from sage.all import *
n = _sage_const_33706105179137483720382763858941811011514787082216064845474913024213096359 
print(f"Is prime: {is_prime(n)}")
if not is_prime(n):
    print(f"Factors: {n.factor()}")

