

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/debug_logs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_433 = Integer(433); _sage_const_3623 = Integer(3623); _sage_const_4507 = Integer(4507); _sage_const_1608913 = Integer(1608913); _sage_const_62107033127 = Integer(62107033127)
from sage.all import *
import ast
import sys

def solve():
    with open('/home/sage/repo/challenges/incu/data.txt', 'r') as f:
        content = f.read().strip()
    parts = content.split('\n')
    params = ast.literal_eval(parts[_sage_const_0 ])
    ciphertexts = ast.literal_eval(parts[_sage_const_1 ])
    p = params['p']
    roots = params['roots']
    factors_list = [(_sage_const_2 , _sage_const_4 ), (_sage_const_5 , _sage_const_2 ), (_sage_const_433 , _sage_const_1 ), (_sage_const_3623 , _sage_const_1 ), (_sage_const_4507 , _sage_const_1 ), (_sage_const_1608913 , _sage_const_1 ), (_sage_const_62107033127 , _sage_const_1 )]
    q = _sage_const_1 
    for b, e in factors_list: q *= b**e
    Fp = GF(p)
    g = Fp.multiplicative_generator()
    h = g**((p-_sage_const_1 ) // q)
    
    print(f"h order: {h.order()}")
    print(f"expected q: {q}")
    
    root_logs = []
    exponent_to_subgroup = (p-_sage_const_1 ) // q
    for i, r in enumerate(roots):
        r_sub = Fp(r)**exponent_to_subgroup
        try:
            print(f"  Computing log for root {i}...", end="")
            sys.stdout.flush()
            l = discrete_log(r_sub, h, ord=q)
            root_logs.append(l)
            print(" Done")
        except Exception as e:
            print(f" FAILED: {e}")
            import traceback
            traceback.print_exc()
            sys.stdout.flush()
            break

solve()

