

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/factor_full.sage
from sage.all_cmdline import *   # import sage library

_sage_const_75649310163467338537242488401191577447135093741127329417060926665079335289551 = Integer(75649310163467338537242488401191577447135093741127329417060926665079335289551); _sage_const_1 = Integer(1)
from sage.all import *

p = _sage_const_75649310163467338537242488401191577447135093741127329417060926665079335289551 
print(f"Factorizing p-1 for p={p}")
f = (p-_sage_const_1 ).factor()
print(f)

