

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/factor_p.sage
from sage.all_cmdline import *   # import sage library

_sage_const_77784259852713049489466853696754794269573634943928106116666017936933247345201 = Integer(77784259852713049489466853696754794269573634943928106116666017936933247345201); _sage_const_1 = Integer(1)
from sage.all import *

def solve():
    p = _sage_const_77784259852713049489466853696754794269573634943928106116666017936933247345201 
    factors = (p-_sage_const_1 ).factor()
    print(factors)

if __name__ == "__main__":
    solve()

