

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/solve_simple.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_128 = Integer(128); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8)
from sage.all import *
import ast
import sys

def solve():
    with open('/home/sage/repo/challenges/incu/data.txt', 'r') as f:
        content = f.read().strip()
    parts = content.split('\n')
    params = ast.literal_eval(parts[_sage_const_0 ])
    ciphertexts = ast.literal_eval(parts[_sage_const_1 ])
    p = params['p']
    roots = params['roots']
    ciphertexts = ciphertexts
    
    # Fully factor p-1 carefully
    p_minus_1 = p - _sage_const_1 
    factors = p_minus_1.factor()
    print(f"Factors of p-1: {factors}")
    
    # We take all factors that are manageable
    # Let's take all except the last one (which is huge)
    manageable_factors = factors[:-_sage_const_1 ]
    q = ZZ(_sage_const_1 )
    for b, e in manageable_factors:
        q *= b**e
    
    print(f"Subgroup order q: {q} (~{float(log(q, _sage_const_2 )):.2f} bits)")
    
    Fp = GF(p)
    g = Fp.multiplicative_generator()
    h = g**((p-_sage_const_1 )//q)
    
    root_logs = []
    exponent = (p-_sage_const_1 )//q
    for i, r in enumerate(roots):
        print(f"Root {i}...", end="")
        sys.stdout.flush()
        r_sub = Fp(r)**exponent
        # Use discrete_log with known factorization for stability
        try:
            l = r_sub.discrete_log(h)
            root_logs.append(l)
            print(" Done")
        except Exception as e:
            print(f" Failed: {e}")
            # Try modulo each factor
            l_val = ZZ(_sage_const_0 )
            m_val = ZZ(_sage_const_1 )
            for b, e in manageable_factors:
                mi = b**e
                hi = h**(q//mi)
                ri = r_sub**(q//mi)
                li = discrete_log(ri, hi, ord=mi)
                l_val = crt([l_val, li], [m_val, mi])
                m_val *= mi
            root_logs.append(l_val)
            print(" Fixed with manual PH")
        sys.stdout.flush()

    def solve_ct(ct):
        l_c = (Fp(ct)**exponent).discrete_log(h)
        n = _sage_const_64 
        M = Matrix(ZZ, n+_sage_const_2 , n+_sage_const_2 )
        K = _sage_const_2 **_sage_const_128 
        for i in range(n):
            M[i, i] = _sage_const_2 
            M[i, n+_sage_const_1 ] = root_logs[i] * K
        M[n, n] = _sage_const_1 
        M[n, n+_sage_const_1 ] = l_c * K
        M[n+_sage_const_1 , n+_sage_const_1 ] = q * K
        M[n+_sage_const_1 , :n] = [_sage_const_1 ]*n
        
        B = M.LLL()
        for row in B:
            if abs(row[n]) == _sage_const_1  and row[n+_sage_const_1 ] == _sage_const_0 :
                sgn = -row[n]
                bits = [int((sgn * row[j] + _sage_const_1 ) // _sage_const_2 ) for j in range(n)]
                if all(b in [_sage_const_0 , _sage_const_1 ] for b in bits):
                    return bits
        return None

    all_bits = []
    for ct in ciphertexts:
        res = solve_ct(ct)
        if res: all_bits.extend(res)
        else: all_bits.extend([_sage_const_0 ]*_sage_const_64 )
    
    val = sum(int(b) << i for i, b in enumerate(all_bits))
    print(f"RESULT: {val.to_bytes((val.bit_length()+_sage_const_7 )//_sage_const_8 , 'big')}")

if __name__ == "__main__":
    solve()

