

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/solve_manual_ph.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_433 = Integer(433); _sage_const_3623 = Integer(3623); _sage_const_4507 = Integer(4507); _sage_const_1608913 = Integer(1608913); _sage_const_62107033127 = Integer(62107033127)
from sage.all import *
import ast
import sys

def solve():
    with open('/home/sage/repo/challenges/incu/data.txt', 'r') as f:
        content = f.read().strip()
    parts = content.split('\n')
    params = ast.literal_eval(parts[_sage_const_0 ])
    ciphertexts = ast.literal_eval(parts[_sage_const_1 ])
    p = params['p']
    roots = params['roots']
    factors_list = [(_sage_const_2 , _sage_const_4 ), (_sage_const_5 , _sage_const_2 ), (_sage_const_433 , _sage_const_1 ), (_sage_const_3623 , _sage_const_1 ), (_sage_const_4507 , _sage_const_1 ), (_sage_const_1608913 , _sage_const_1 ), (_sage_const_62107033127 , _sage_const_1 )]
    q = _sage_const_1 
    for b, e in factors_list: q *= b**e
    Fp = GF(p)
    g = Fp.multiplicative_generator()
    h = g**((p-_sage_const_1 ) // q)
    
    root_logs = []
    exponent_to_subgroup = (p-_sage_const_1 ) // q
    for i, r in enumerate(roots):
        print(f"Root {i}...")
        sys.stdout.flush()
        r_sub = Fp(r)**exponent_to_subgroup
        try:
            # Try manual PH step by step to find where it fails
            l_val = _sage_const_0 
            curr_mod = _sage_const_1 
            for pi, ei in factors_list:
                qi = pi**ei
                # Project back to subgroup of order qi
                hi = h**(q // qi)
                ri = r_sub**(q // qi)
                li = discrete_log(ri, hi, ord=qi)
                # CRT combination
                l_val = crt([l_val, li], [curr_mod, qi])
                curr_mod *= qi
            
            root_logs.append(l_val)
        except Exception as e:
            print(f"Error at root {i}: {e}")
            import traceback
            traceback.print_exc()
            sys.stdout.flush()
            return

    print("All logs done. Solving blocks...")
    # ... rest of solve logic ...
solve()

