

# This file was *autogenerated* from the file /home/sage/repo/challenges/incu/test_dl.sage
from sage.all_cmdline import *   # import sage library

_sage_const_75649310163467338537242488401191577447135093741127329417060926665079335289551 = Integer(75649310163467338537242488401191577447135093741127329417060926665079335289551); _sage_const_5233803906150819415957 = Integer(5233803906150819415957); _sage_const_1 = Integer(1); _sage_const_123456789 = Integer(123456789)
from sage.all import *
import time

p = _sage_const_75649310163467338537242488401191577447135093741127329417060926665079335289551 
factor_72 = _sage_const_5233803906150819415957 
exponent = (p-_sage_const_1 ) // factor_72
Fp = GF(p)
g = Fp.multiplicative_generator()
h = g**exponent

# Target
target = h**_sage_const_123456789 

print(f"Starting DL test in subgroup of order {factor_72}...")
start = time.time()
l = discrete_log(target, h, ord=factor_72)
end = time.time()
print(f"Done! Log: {l}")
print(f"Time: {end - start:.2f} seconds")

