

# This file was *autogenerated* from the file /home/sage/repo/challenges/a-dance-of-add-and-mul/check_invariants.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab = Integer(0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2)
p = _sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab 
K = GF(p)
E = EllipticCurve(K, (_sage_const_0 , _sage_const_4 ))
dv = E.elementary_divisors()
print(f"Invariants: {dv}")
n = E.order()
print(f"n factorized: {n.factor()}")
for q, e in n.factor():
    if e >= _sage_const_2 :
        print(f"Prime factor {q}^{e} might be in d1")

