

# This file was *autogenerated* from the file /home/sage/repo/challenges/a-dance-of-add-and-mul/check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab = Integer(0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1)
p = _sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab 
K = GF(p)
E = EllipticCurve(K, (_sage_const_0 , _sage_const_4 ))
n = E.order()
print(f"Order: {n}")
print(f"Factorized order: {n.factor()}")
gens = E.gens()
print(f"Generators: {len(gens)}")
for i, g in enumerate(gens):
    print(f"G{i+_sage_const_1 } order: {g.order()}")

