

# This file was *autogenerated* from the file /home/sage/repo/challenges/xorshift-stream/solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_13 = Integer(13); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_17 = Integer(17); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_63 = Integer(63)
from sage.all import *

def solve():
    print("Step 1")
    R = GF(_sage_const_2 )
    M = identity_matrix(R, _sage_const_64 )
    M_L13 = identity_matrix(R, _sage_const_64 )
    for i in range(_sage_const_64  - _sage_const_13 ):
        M_L13[i + _sage_const_13 , i] += _sage_const_1 
    M = M_L13 * M
    M_R7 = identity_matrix(R, _sage_const_64 )
    for i in range(_sage_const_64  - _sage_const_7 ):
        M_R7[i, i + _sage_const_7 ] += _sage_const_1 
    M = M_R7 * M
    M_L17 = identity_matrix(R, _sage_const_64 )
    for i in range(_sage_const_64  - _sage_const_17 ):
        M_L17[i + _sage_const_17 , i] += _sage_const_1 
    M = M_L17 * M
    T = M
    print("Step 2")
    ct_hex = "142d35c86db4e4bb82ca5965ca1d6bd55c0ffeb35c8a5825f00819821cd775c4c091391f5eb5671b251f5722f1b47e539122f7e5eadc00eee8a6a631928a0c14c57c7e05b6575067c336090f85618c8e181eeddbb3c6e177ad0f9b16d23c777b313e62b877148f06014e8bf3bc156bf88eedd123ba513dfd6fcb32446e41a5b719412939f5b98ffd54c2b5e44f4f7a927ecaff337cddf19fa4e38cbe01162a1b54bb43b0678adf2801d893655a74c656779f9a807c3125b5a30f4800a8"
    ct = bytes.fromhex(ct_hex)
    A = []
    b = []
    for i in range(_sage_const_4 ):
        ct_block = int.from_bytes(ct[i*_sage_const_8  : i*_sage_const_8  + _sage_const_8 ], "little")
        Ti = T**(i+_sage_const_1 )
        for j in range(_sage_const_8 ):
            A.append(Ti.row(j*_sage_const_8  + _sage_const_7 ))
            b.append(R((ct_block >> (j*_sage_const_8  + _sage_const_7 )) & _sage_const_1 ))
            A.append(Ti.row(j*_sage_const_8  + _sage_const_5 ))
            b.append(R(((ct_block >> (j*_sage_const_8  + _sage_const_5 )) & _sage_const_1 ) ** _sage_const_1 ))
            A.append(Ti.row(j*_sage_const_8  + _sage_const_6 ) + Ti.row(j*_sage_const_8  + _sage_const_4 ))
            b.append(R(((ct_block >> (j*_sage_const_8  + _sage_const_6 )) ** (ct_block >> (j*_sage_const_8  + _sage_const_4 )) ** _sage_const_1 ) & _sage_const_1 ))
    print("Step 3")
    A_mat = matrix(R, A)
    b_vec = vector(R, b)
    S0_sol = A_mat.solve_right(b_vec)
    print("Step 4")
    S0_val = _sage_const_0 
    for idx, bit in enumerate(S0_sol):
        if bit: S0_val |= (_sage_const_1  << idx)
    def get_next(state):
        state = (state ** (state << _sage_const_13 )) % _sage_const_2 **_sage_const_64 
        state = (state ** (state >> _sage_const_7 )) % _sage_const_2 **_sage_const_64 
        state = (state ** (state << _sage_const_17 )) % _sage_const_2 **_sage_const_64 
        return state
    curr_state = S0_val
    dec = b""
    for i in range(_sage_const_0 , len(ct), _sage_const_8 ):
        curr_state = get_next(curr_state)
        block = ct[i : i + _sage_const_8 ]
        pt_int = int.from_bytes(block, "little") ** curr_state
        dec += pt_int.to_bytes(_sage_const_8 , "little")[:len(block)]
    print(f"Decrypted: {dec}")
    key_len = _sage_const_63 
    key = bytes.fromhex(dec[:_sage_const_2 *key_len].decode())
    tag = dec[_sage_const_2 *key_len:]
    flag = bytes([k ** t for k, t in zip(key, tag)])
    print(f"FLAG: {flag.decode()}")

solve()

