
import json
import sys
import os
from Crypto.Util.number import long_to_bytes
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

# Add project root to path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PROJECT_ROOT)

try:
    from solver.modules.lattice import solve_hnp
except ImportError:
    print("Failed to import solver.modules.lattice")
    sys.exit(1)

# P-256 Parameters
p = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
a = 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc
b = 0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b
Gx = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296
Gy = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5
order = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551

def decrypt_flag(x, ct_hex):
    # Calculate shared secret
    # Q_server = x * G (We recovered x)
    # Exch: k was chosen by server.
    # Exch: (kQ).x() used as key.
    # Wait, in exchange function:
    # k = rng.next(None)
    # AES key is (kQ).x()
    # AES iv is high 128 bits.
    # WE don't know k.
    # BUT we recovered x (private key of server?)
    # Wait.
    # Challenge calls: Q = x * G.
    # Sign: s = k^-1 (z + x r).
    # Exchange: key = (k Q).x().
    # Q is PUBLIC KEY of server. x is PRIVATE KEY.
    # k is ephemeral nonce.
    # If we recover x, we know PROOF of private key?
    # But for EXCHANGE, the server uses x to sign? No.
    # Exchange uses k and Q.
    # Wait.
    # Q = xG.
    # key = (k Q).x() = (k x G).x().
    # Only server knows x? Yes.
    # Only server knows k? Yes.
    # Server computes key.
    # Server sends: AES(key, msg).
    # Wait.
    # The server sends:
    # AES.new(...).encrypt(...)
    # It sends ciphertext. It does NOT send kQ or anything.
    # Unless...
    # `AES.new(long_to_bytes(int((k*Q).x())%(2**128), ...), ..., iv=...)`
    # All derivation comes from `(kQ).x()`.
    # `k` is generated by `rng.next(None)`.
    # `k = H(C_ex)`.
    # How do we get `k` or `C_ex`?
    # Recovering `x` doesn't give us `k`.
    # Recovering `x` allows us to sign? Yes.
    # But exchange is encrypted.
    # UNLESS... we can predict `k`?
    # No.
    
    # Wait!
    # If we know x, we can find k from ANY signature!
    # k = s^-1 (z + x r) mod n.
    # So we can recover ALL past k_i.
    # k_i = H(C_i).
    # We can't recover C_i.
    # BUT!
    # exchange happened AFTER test signatures.
    # C_ex = C_last + 1 + h(m_last).
    # Can we find C_last? No.
    # Can we find C_ex? No.
    
    # Is there a relation we missed?
    # "Groups, Rings, and Fields. But only groups (and modules!)"
    
    # Maybe the "Exchange" function logic has a flaw?
    # k = rng.next(None).
    # It uses AES-CBC.
    
    pass

def solve():
    with open("signatures.json", "r") as f:
        data = json.load(f)
        
    sigs = []
    for s in data["sigs"]:
        sigs.append((s['r'], s['s'], s['h']))
        
    print(f"Loaded {len(sigs)} signatures.")
    
    # Try HNP with nonce_bits estimation
    # Bias is 256 - log2(n) approx 0?
    # But maybe significant bits are effectively 0?
    
    # Let's try to assume nonce_bits = 252 (leak 4 bits).
    # Or start high.
    
    recovered_d = None
    
    for bits in range(256, 240, -1):
        print(f"Testing nonce_bits={bits}")
        d = solve_hnp(sigs, order, bits)
        if d:
            print(f"Recovered x: {d}")
            recovered_d = d
            break
            
    if not recovered_d:
        print("Failed to recover x")
        return

    # If x is recovered, verify it against public key Q if known
    # Q in data["Q"]
    # Check x*G == Q
    
    print("Verifying against signatures...")
    # k = s^-1(z + xr)
    # Check if this k makes sense?
    # But we can't fully verify without knowing C.
    
    # BUT wait!
    # If we have x, we can calculate K for the exchange?
    # No, we can't.
    # This implies there must be a way to predict K.
    # OR...
    # Maybe the key IS derived from x?
    # "AES.new(long_to_bytes(int((k*Q).x())%(2**128)...)"
    # key is derived from kQ.
    # If we don't know k, we assume we can't decrypt.
    # UNLESS k is predictable.
    
    # What if k is recovered from sigs?
    # k_last.
    # C_last?
    # If we can't invert H, we are stuck.
    
    # Is it possible H is weak?
    # No.
    
    print("FLAG might be encrypted in 'ct'. Decryption requires k.")

if __name__ == "__main__":
    solve()
